apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
        labels:
          app: myspringbootapp
    spec: 
      containers:
      - name: container1
        image: najamrizvi3/imageproje:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata: 
  name: service
  namespace: default
spec:
  selector:
      app: myspringbootapp
  ports: 
  - protocol: TCP
    port: 8088
    targetPort: 8088
  type: LoadBalancer

